CUDA_VISIBLE_DEVICES=0,1,2 torchrun --standalone --nnodes 1 --nproc-per-node 3 vla-scripts/finetune.py \
    --vlm_path pretrained_models/prism-qwen25-extra-dinosiglip-224px-0_5b \
    --config_file_path pretrained_models/configs \
    --data_root_dir /data/public/NAS/LIBERO_modified \
    --dataset_name needle_all \
    --run_root_dir outputs \
    --use_film False \
    --num_images_in_input 3 \
    --use_proprio True \
    --use_lora True \
    --use_fz False \
    --use_minivlm True \
    --image_aug True \
    --num_steps_before_decay 50000 \
    --max_steps 50005 \
    --save_freq 5000 \
    --save_latest_checkpoint_only False \
    --merge_lora_during_training False \
    --resume True \
    --resume_step 30000 \
    --resum_vla_path /data/public/NAS/VLA-Adapter/outputs/configs--30000_chkpt \
    --batch_size 4 \
    --grad_accumulation_steps 1 \
    --learning_rate 2e-4 \
    --lora_rank 64 \
    --use_pro_version True \
    --wandb_entity "najyeol99-daegu-gyeongbuk-institute-of-science-technology" \
    --wandb_project "needle_insertion" \
    --run_id_note VLA-Adapter--needle_all--$current_time
    